-- Seed 1 sample member row.
-- member_code is auto-generated by trg_assign_member_code (ME-XXXX).
-- sku is generated automatically from member_code.

INSERT INTO public.members (
  profile_id,
  full_name,
  contact_number,
  email_address,
  birthdate,
  gender,
  image_url
)
VALUES (
  NULL,
  'JUAN DELA CRUZ',
  '09123456789',
  'juan.delacruz@example.com',
  '2000-01-15',
  'MALE',
  NULL
)
RETURNING member_id, member_code, sku, full_name, created_at;

